### ISSUE TITLE
Separate Level 1 and 2 hardening as a config.

### ISSUE THREAD

**Issue by amonza1** [oguya/cis-ubuntu-14-ansible#17]
It would be super convenient to be able to chose between level one and level two hardening as a configurable value.  Currently, if I wanted to harden a server only to level one, I would need to comment out the level 2 tasks.  I'd like to ability to set a variable at runtime or in a config to let me chose the level of hardening dynamically.

**Comment by oguya** [comment]
Just run the playbook & specify either `level-1` or `level-2` tag.
For example:

```
ansible-playbook cis.yml -i hosts --ask-become-pass --tags=level-1
ansible-playbook cis.yml -i hosts --ask-become-pass --tags=level-2
```

By the way, this is all documented in the [README](https://github.com/oguya/cis-ubuntu-14-ansible/blob/master/README.md#usage).

**Comment by amonza1** [comment]
Sorry I missed that in the readme.  I don't know how you could make it more obvious; it's on me.  I closed the associate pull request.  Thanks for responding.
