### ISSUE TITLE
Build is failing because aideinit is not coming back

### ISSUE THREAD

**Issue by amonza1** [oguya/cis-ubuntu-14-ansible#20]
main.yml in the handler needs to be fixed to address the issue. The -y flag needs to be set in the aideinit command so that it overwrites the existing information.

**Comment by oguya** [comment]
I've also been wondering why `aideinit` is failing on Travis-CI build environment yet it works on my local test VMs. I don't know if this is a problem with the build environment.

**Comment by amonza1** [comment]
It takes a couple of minutes to run on my VM.  Part of the problem could be that the VM being used by Travis is bursty, so after a certain period of time, you only get about 10% of 2 cpu, not two full CPU.  With how many tasks are required beforehand, it possible that it's just running out of CPU and not coming back in 10 minutes.  I'll try running it with travis_wait 30t to see if that's the issue.

**Comment by amonza1** [comment]
I ran it with travis_wait and the entire build came back.  It's still listed as failed because of two items: 13.20 (ensure shadow group is empty), is throwing an error.  Also, app armor profiles aren't installed, so when the app armor handler runs, it throws an error that the profiles aren't present.  I'm going to try to finish fixing both and then submit a pull request to you that fixes all of the build issues.

**Comment by oguya** [comment]
Don't worry too much about Section 13.20, it's a manual remediation task and therefore I decided to ignore it on ansible. See commit: 4c007b3301594963534213b528a17707962fa7dd

**Comment by oguya** [comment]
I think the solution is to ignore tasks that call `apparmor` & `aideinit` processes on [travis.yml#L27](https://github.com/oguya/cis-ubuntu-14-ansible/blob/master/.travis.yml#L27). After all, we've tested several it times on local Ubuntu 14.04 test vms.

**Comment by oguya** [comment]
@amonza1 please confirm if you're OK with this fix.
See commit: b153579
